### Create Order
POST http://localhost:8000/order HTTP/1.1
Content-Type: application/json

{
    "id": "order-1",
    "price": 100.0,
    "tax": 10.0
}

### List Orders
GET http://localhost:8000/order HTTP/1.1
